config/routes.rb
SampleApp::Application.routes.draw do
  resources :projects do
    resources :tasks, only: [:create, :destroy, :edit, :update, :show] do
      post :change_status
    end
    resource :tasks ,only: [] do
      post :sort
      post :calculate
    end
  end
  resources :users do
    member do
      get :following, :followers
      post :upload_image
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li
          * #{msg}

app/views/shared/_feed.html.haml
- if @feed_items.any?
  %ol.tasks
    = render partial: 'shared/feed_item', collection: @feed_items
  = will_paginate @feed_items

app/views/shared/_feed_item.html.haml
%tr
  %td= link_to "delete", project_task_path(@project, feed_item), method: :delete, |
    data: { confirm: "本当に削除しますか？" },               |
    title: feed_item.content                      |
  %td= link_to "edit", edit_project_task_path(@project, feed_item)
  %td= feed_item.content
  %td= feed_item.status
  - unless feed_item.done?
    %td= link_to acition_name(feed_item), project_task_change_status_path(@project, feed_item, action_name: acition_name(feed_item)), method: :post, class: "btn btn-info"

/ %li{:id => "#{feed_item.id}"}
/   %span.content= feed_item.content
/   %span.content
/     status :
/     = feed_item.status
/   %span.timestamp
/     Posted #{time_ago_in_words(feed_item.created_at)} ago.
/   / - if current_user?(feed_item.user)

app/views/shared/_micropost_form.html.haml
= form_for(@micropost) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.text_area :content, placeholder: "Compose new micropost..."
  = f.submit "Post", class: "btn btn-large btn-primary"

app/views/shared/_stats.html.haml
- @user ||= current_user
.stats
  %a{:href => "#{following_user_path(@user)}"}
    %strong#following.stat
      = @user.followed_users.count
    following
  %a{:href => "#{followers_user_path(@user)}"}
    %strong#followers.stat
      = @user.followers.count
    followers

app/views/shared/_task_form.html.haml
= form_for(@task, url: project_tasks_path(project_id: @project)) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.text_field :name, placeholder: "タスク名を記入してください"
  .field.pull-left.task_field
    = f.text_area :content, placeholder: "タスク内容を記入してください"
  = f.submit "Post", class: "btn btn-large btn-primary task_form_button"

app/views/shared/_user_info.html.haml
%a{:href => "#{user_path(current_user)}"}
  = gravatar_for current_user, size: 52
%h1
  = current_user.name
%span
  = link_to "view my profile", current_user
%span
  = pluralize(current_user.tasks.count, "task")