config/routes.rb
SampleApp::Application.routes.draw do
  resources :projects do
    resources :tasks, only: [:create, :destroy, :edit, :update, :show] do
      post :change_status
    end
    resource :tasks ,only: [] do
      post :sort
      post :calculate
    end
  end
  resources :users do
    member do
      get :following, :followers
      post :upload_image
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks, dependent: :destroy

  def term
    self.start_date.bussiness_dates(dailies)
  end

  def dailies
    tasks.map(&:dailies).flatten.map(&:the_date).uniq.size
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    if signed_in?
      @feed_items = @project.tasks.order(:order)
      @task = Task.new(project_id: @project.id)
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :user_id, :start_date)
    end
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :start_date
    = f.date_field :start_date
  .actions
    = f.submit 'Save', { class: "btn btn-large btn-primary" }

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
\|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Listing projects

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @projects.each do |project|
      %tr
        %td= project.name
        %td= link_to 'Show', project
        %td= link_to 'Edit', edit_project_path(project)
        %td= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
%p
  %b プロジェクト名:
  = @project.name

= link_to "Edit", edit_project_path(@project)
\|
= link_to "Back", projects_path

= render "shared/task_form"
.clearfix
  =button_to "自動計算", calculate_project_tasks_path(@project), class: "btn btn-primary pull-right"

- if @feed_items.any?
  .task_table_container
    %table.table.table-bordered.task_table{ id: "project_table" }
      %thead
        %tr
          %th= "内容"
          %th= "担当者"
          %th.status= "ステータス"
          %th
          %th.plane_time= "予定"
          - @project.term.each do |_date|
            %th.task_date
              = _date.strftime("%-d")
              = _date.youbi
          %th
      %tbody.sortable
        - @feed_items.each do |feed_item|
          %tr{ class: "#{ 'done' if feed_item.done? } #{ 'not_started' if feed_item.not_started? } task_row", data: { "task_id": feed_item.id } }
            %td
              %label.feed_item_title #{feed_item.name}
            %td= collection_select :task, :user_id, User.all, :id, :name, { :selected => feed_item.user.id }, { :class => "task_user_field" }
            - unless feed_item.done?
              %td{ style: "text-align: center;" }= link_to acition_name(feed_item), project_task_change_status_path(@project, feed_item, action_name: acition_name(feed_item)), method: :post, class: "btn btn-info"
            -else
              %td{ style: "text-align: center;" }= status_name(feed_item.status)
            %td= link_to "delete", project_task_path(@project, feed_item), method: :delete,
              data: { confirm: "本当に削除しますか？" }, title: feed_item.content
            %td.plane_time{ style: "text-align: center;" }
              %input.planed_time_field{ type: "text", value: feed_item.planed_time }
            - @project.term.each do |date|
              %td
                = feed_item.dailies.find_by(the_date: date).try(:planed_time)
            %td= link_to "delete", project_task_path(@project, feed_item), method: :delete,
              data: { confirm: "本当に削除しますか？" }, title: feed_item.content

/ = render "tasks/edit_panel"