config/routes.rb
SampleApp::Application.routes.draw do
  resources :projects do
    resources :tasks, only: [:create, :destroy, :edit, :update, :show] do
      post :change_status
    end
    resource :tasks ,only: [] do
      post :sort
      post :calculate
    end
  end
  resources :users do
    member do
      get :following, :followers
      post :upload_image
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    %a{:href => "http://railstutorial.org/"} Rails Tutorial
    by Michael Hartl
  %nav
    %ul
      %li= link_to "About",   about_path
      %li= link_to "Contact", contact_path
      %li
        %a{:href => "http://news.railstutorial.org/"} News

app/views/layouts/_header.html.haml
%body
  %header
    .navbar.navbar-default.navbar-fixed-top
      .navbar-header
        = link_to "sample app", root_path, class: "navbar-brand"
      %nav.navbar-collapse.collapse
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Home", root_path
          %li= link_to "Help", help_path
          - if signed_in?
            %li= link_to "Users", users_path
            %li#fat-menu.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                Account
                %b.caret
              %ul.dropdown-menu.pull-right
                %li= link_to "Profile", current_user
                %li= link_to "Settings", edit_user_path(current_user)
                %li.divider
                %li
                  = link_to "Sign out", signout_path, method: "delete"
          - else
            %li= link_to "Sign in", signin_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= full_title(yield(:title))
    = stylesheet_link_tag "application", media: "all", |
      "data-turbolinks-track" => true                  |
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        %div{:class => "alert alert-#{key}"}= value
      = yield
      / = render 'layouts/footer'
      / = debug(params) if Rails.env.development?